### ISSUE TITLE
building wheel with pip fails

### ISSUE THREAD

**Issue by khintz** [metno/titanlib#21]
I just ran into a minor issue when installing titanlib with pip
`pip install titanlib`
which fails for me when building the wheel for titanlib.
```
Building wheels for collected packages: titanlib
  Building wheel for titanlib (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [207 lines of output]
```
The error is as follows
```
In file included from src/util.cpp:3:
      /usr/include/proj_api.h:37:2: error: #error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
         37 | #error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
            |  ^~~~~
      error: command '/usr/bin/gcc' failed with exit code 1
```
The installation of titanlib succeeds if I add CFLAGS:
`CFLAGS="-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H" pip install titanlib`
In this environment, I am using PROJ 6.3.1. I can test if it also happens for newer releases.

**Comment by tnipen** [comment]
Hmm, that is weird because we removed the proj4 dependency in v0.3.0. What version are you trying to install?
