### ISSUE TITLE
Documentation: wrong name of string 

### ISSUE THREAD

**Issue by Francesco-Uboldi** [metno/titanlib#29]
In [namespace reference ](https://metno.github.io/titanlib/0.3.3/namespacetitanlib.html), in the parameter description for `sct_resistant()`, the strings reported for the parameter `background_elab_type` are: `vertical_profile, vertical_profile_Theil_Sen, mean_outer_circle, external`: this is not correct.
They should be instead: `VerticalProfile, VerticalProfileTheilSen, MeanOuterCircle, MedianOuterCircle, External`

**Comment by cristianlussana** [comment]
Thanks Francesco. I should have fixed it.
Cr
